import type { WifiNetwork } from '../types'

export const demoNetworks: WifiNetwork[] = [
  {
    id: 'demo-home',
    ssid: 'Bayt_5G',
    bssid: '••:••:••:7A:21:10',
    signal: 92,
    channel: 36,
    frequency: 5180,
    security: 'WPA3',
    connected: true,
    owned: true,
    isDemo: true,
    audit: {
      score: 92,
      level: 'excellent',
      guesses: 3.1e22,
      crackTime: 'أكثر من 10 آلاف سنة',
      testedAt: new Date(Date.now() - 18 * 60_000).toISOString(),
      findings: [],
    },
  },
  {
    id: 'demo-office',
    ssid: 'Studio_Network',
    bssid: '••:••:••:18:C2:4F',
    signal: 76,
    channel: 11,
    frequency: 2462,
    security: 'WPA2',
    owned: true,
    isDemo: true,
    audit: {
      score: 71,
      level: 'good',
      guesses: 9.2e12,
      crackTime: 'نحو سنة و6 أشهر',
      testedAt: new Date(Date.now() - 2 * 60 * 60_000).toISOString(),
      findings: ['يمكن زيادة طول العبارة السرية.'],
    },
  },
  {
    id: 'demo-iot',
    ssid: 'Home_IoT',
    bssid: '••:••:••:02:8B:91',
    signal: 61,
    channel: 6,
    frequency: 2437,
    security: 'WPA2',
    owned: true,
    isDemo: true,
    audit: {
      score: 38,
      level: 'attention',
      guesses: 1.4e8,
      crackTime: 'قرابة 23 دقيقة',
      testedAt: new Date(Date.now() - 25 * 60 * 60_000).toISOString(),
      findings: ['نمط شائع أو متوقع', 'العبارة أقصر من الموصى به'],
    },
  },
  {
    id: 'demo-guest',
    ssid: 'Majlis_Guest',
    bssid: '••:••:••:A4:31:08',
    signal: 48,
    channel: 1,
    frequency: 2412,
    security: 'WPA2/WPA3',
    owned: true,
    isDemo: true,
  },
]
